### ISSUE TITLE
Add a method for waiting an amount of time before install the update when app is in background

### ISSUE THREAD

**Issue by luca-sharryland** [Cap-go/capacitor-updater#100]
Hi, I currently use the self-hosted autoupdate method.
I tested the behaviour of using cancelDelay() and delayUpdate() but both refer only to the next time app goes in background...
It could be useful if we could choose an amount of time before the app installs the update.
The main reason is that possibly the user is typing any information in a form, and puts the app in background for searching missing fields (like cvc, iban etc..), but in this particular scenario, if there is a pending update, he will lose all previously typed information.

Thanks!

**Comment by matteoinfantino** [comment]
This could be really useful

**Comment by lincolnthree** [comment]
I don't want to speak for him, but @riderx and I have discussed this issue previously, and I think he was enthusiastic about it. Essentially this would be a configuration parameter in `capacitor.config.ts` like so:

```
/**
 * The time in milliseconds for how long the application must remain backgrounded before a pending update will be applied. This allows some control over when the app is considered 'Idle' or 'safe to update' -- e.g. when the user is not actively using it.
 */
backgroundUpdateDelay: 10000
```

Process workflow:
1. Every time the app is sent into the background, we would need to save a timestamp.
2.Then when the app is brought into the foreground again, we only do update checks/tasks if the elapsed time is greater than the difference between the current time and the saved timestamp.
3. Regardless of whether an update happened or not at this time, the timestamp should be cleared until the app is backgrounded again, at which point this process starts over at (1).

**Comment by luca-sharryland** [comment]
@lincolnthree  Of course, that's what I need.
Maybe it could be possible to check also if the user kills the app to force an update even if the backgroundUpdateDelay isn't elapsed

**Comment by riderx** [comment]
Hey @luca-sharryland thanks for the report.
In **V3** `delayUpdate` will delay to one backgrounding.
So the user download the update while he is filling the form you call `delayUpdate` if the user go in background to fetch info and come back, he don't get the update ( if he is still in the form call it again to prevent if he go again)

speaking with some users including @lincolnthree i saw this was far than perfect, so in V4 ( who going to be released Monday), you gonna more option like date, app kill, or native version minimum.

**Comment by luca-sharryland** [comment]
Hi @riderx thanks for this plugin, it's great!
I looked at the new source code (alpha.56) and want to ask you for some clarifications, if possible.
when I use kind: date for setDelay the update will be installed after the value is elapsed, but if the user kills the app before, what will happen? cause it could be useful to force installation before in this case.
My intent is to have 2 ways to complete installations:
1 - after 5 minutes in background
2 - after the user kills the app

Thanks in advance

**Comment by riderx** [comment]
For now, this value is unique but I can make it as a list, and if one of the condition of the list is valid then the update happen.
So you could put date, nativeVersion and time, and if any of them is valid the delay is flush and update happen.
What do you think ?

**Comment by luca-sharryland** [comment]
> For now, this value is unique but I can make it as a list, and if one of the condition of the list is valid then the update happen. So you could put date, nativeVersion and time, and if any of them is valid the delay is flush and update happen. What do you think ?

I think this could be the best solution!
P.s. do you have an idea about the time required for this development? 
Thanks

**Comment by riderx** [comment]
it will happen this week

**Comment by luca-sharryland** [comment]
@riderx Maybe I can help you to code this feature if you want, I'm at your disposal.
Let me know

**Comment by riderx** [comment]
do you know swift and java ?
if yes let go !
i have seen a way to do it even after release without breaking change.
with key multidelay

**Comment by luca-sharryland** [comment]
> do you know swift and java ? if yes let go ! i have seen a way to do it even after release without breaking change. with key multidelay

Yes, I'm better with Java, but I can also try with swift. 
So your plan is to add "multidelay" key to the enum "DelayUntilNext"  to manage multiple choices, but in this case setDelay function has to accept a string array for value parameter. We could use a particular string joining format (for avoiding breaking changes, like "kill|background|nativeVersion") and split "|" character, but maybe this isn't the best approach... Let me know your opinion.
From Monday I could start developing this feature.

**Comment by riderx** [comment]
okay wait maybe my idea was not clear.
so current data input is :
```typescript
{
  kind: DelayUntilNext,
  value?: string
}
```
And i was thinking to do :
```typescript
{
  kind: DelayUntilNext,
  value?: string,
  multi?: {
    kind: DelayUntilNext,
    value?: string
  }[]
}
```
Then in java and swift if multi is set then it do add the array directly, otherwise it behaves like before, but in the swift and java store it as one delay in the array list.
So, the main change will be how we store delay, and how we check it. because it goes from a unique object to a list.

**Comment by luca-sharryland** [comment]
I think "Last option" is the best solution
