### ISSUE TITLE
self-hosted keeps request to https://api.capgo.app/updates [ANDROID]

### ISSUE THREAD

**Issue by TheBrown** [Cap-go/capacitor-updater#102]
I have a problem with self-hosted. After I set `autoUpdate: true` in capacitor.config.json it keeps request to https://api.capgo.app/updates not my own server
![image](https://user-images.githubusercontent.com/16058602/189308970-8543551f-43cd-426a-be07-99efd91efc4c.png)

my setup 
![image](https://user-images.githubusercontent.com/16058602/189309320-41ae6929-4710-410c-ba56-dd61d91cb3c3.png)

**Comment by riderx** [comment]
Hello in v4 this var have been renamed : https://docs.capgo.app/upgrade/from-v3-to-v4#auto-update-self-hosted
i need to migrate the doc for v4

**Comment by TheBrown** [comment]
OK, thank you
