### ISSUE TITLE
Our App with capacitor-updater crashes

### ISSUE THREAD

**Issue by colenso** [Cap-go/capacitor-updater#108]
Not able to replicate this on demand but it has been happening to our users since last week and just happened to one of our team members today. 
User is using a iPhone 13 Pro has been using the app just fine. I think an OTA update installed at around 5 PM today and when he tried to use the app again saw a white screen and couldn't do anything with the app. Then when he force quite the app wasn't starting again.

**Comment by luca-sharryland** [comment]
@riderx I think it's related to the ios issue of my pull request (#106).
killing the app the first time seems not to change the current bundle (even if the getBundleInfo function returns the new version code). However, if the previous bundle isn't builtin after the installation, it is deleted. So the app tries to get deleted bundle files and crashes

**Comment by riderx** [comment]
@luca-sharryland did you saw he issue happen again after the merge of your PR, @colenso did you check ?

**Comment by luca-sharryland** [comment]
@riderx yes only in one case, probably not related to multi delay

**Comment by luca-sharryland** [comment]
@riderx unfortunately this bug is not solved.  For the second time, it happens in our production app, always in ios.

**Comment by riderx** [comment]
Did you receive logs in Xcode about that issue?

**Comment by luca-sharryland** [comment]
> Did you receive logs in Xcode about that issue?

No, I've received feedback from a collaborator that was using the production app

**Comment by luca-sharryland** [comment]
@riderx any news for this?

**Comment by riderx** [comment]
@luca-sharryland i need logs to understand the issue, I don't have a way to reproduce. all the apps I have in production have very log crash rate, so i don't know where that can come from

**Comment by luca-sharryland** [comment]
> @luca-sharryland i need logs to understand the issue, I don't have a way to reproduce. all the apps I have in production have very log crash rate, so i don't know where that can come from

there's a way we can save plugin error logs from our app? so we can investigate

**Comment by riderx** [comment]
@luca-peruzzo you can get them here : https://developer.apple.com/news/?id=nra79npr

**Comment by luca-peruzzo** [comment]
> @luca-peruzzo you can get them here : https://developer.apple.com/news/?id=nra79npr

I know how to view crash reports, but the only one I have is not comprehensive
![image](https://user-images.githubusercontent.com/69015314/218963484-1ce47784-d013-4126-b600-9c78da018ff6.png)

**Comment by sethrevelle** [comment]
I am experiencing this issue as well, where intermittently an app will fail crash immediately after launch once an update is pushed.  I pulled following information from xCode when iPad was in this state, I am not sure if it is helpful.

✨  Capacitor-updater: init for device XXX
✨  Capacitor-updater: Getting info for bundle [n73LWaHKYG]
✨  Capacitor-updater: Returning info bundle [{ "id": "n73LWaHKYG", "version": "1.0.413", "downloaded": "2023-06-28T11:22:32.634Z", "checksum": "00b5cfdf", "status": "pending"}]
✨  Capacitor-updater: Getting info for bundle [n73LWaHKYG]
✨  Capacitor-updater: Returning info bundle [{ "id": "n73LWaHKYG", "version": "1.0.413", "downloaded": "2023-06-28T11:22:32.634Z", "checksum": "00b5cfdf", "status": "pending"}]
✨  Capacitor-updater: Wait for 10000 ms, then check for notifyAppReady
✨  Capacitor-updater: Check for update via https://api.capgo.app/updates
✨  Capacitor-updater: Getting info for bundle [n73LWaHKYG]
✨  Capacitor-updater: Returning info bundle [{ "id": "n73LWaHKYG", "version": "1.0.413", "downloaded": "2023-06-28T11:22:32.634Z", "checksum": "00b5cfdf", "status": "pending"}]
✨  Capacitor-updater: Auto-update parameters: InfoObject(platform: Optional("ios"), device_id: Optional("XXX"), app_id: Optional("[y](http://com.servicevanguard.app/)yy"), custom_id: Optional(""), version_build: Optional("1.0"), version_code: Optional("1"), version_os: Optional("16.5.1"), version_name: Optional("1.0.413"), plugin_version: Optional("4.60.0"), is_emulator: Optional(false), is_prod: Optional(false), action: nil, channel: nil)
⚡️  ERROR: Unable to load /var/mobile/Containers/Data/Application/ZZZ/Library/NoCloud/ionic_built_snapshots/n73LWaHKYG
⚡️  This file is the root of your web app and must exist before
⚡️  Capacitor can run. Ensure you've run capacitor copy at least
⚡️  or, if embedding, that this directory exists as a resource directory.

**Comment by riderx** [comment]
I still cannot reproduce, but i found a way to better verify if the folder and the file exist before set them, there a change to improve the issue, otherwise i need your help to find a way to reproduce the issue
