### ISSUE TITLE
Find a way to make the plugin don't do auto update when runned by google bots

### ISSUE THREAD

**Issue by riderx** [Cap-go/capacitor-updater#117]
i did try to detect emulator  in prod mode to cancel them to call auto-update but seems, google is running real device

**Comment by lincolnthree** [comment]
@riderx Hey, long time! I hope all is well.

What's the idea / reasoning for this feature? Just curious as I'm not sure this is something that should be handled by the plugin itself (though I think giving users a way to prevent auto-updating would be a good idea via a method or API.)

**Comment by riderx** [comment]
Hey @lincolnthree that a report i got from users, when their CI/CD send app to google and Apple the plugin ask for update and that count around 30 devices by each version publish to beta channel/testflight. 
So that a problem, and that have to be detect in Capgo and in updater side, at least the updater should send enough info to let Capgo know when it's a bot device.
More clear ?

**Comment by lincolnthree** [comment]
@riderx Ah yeah that makes sense! I was kind of wondering what could be the need for this. Maybe if Apple / Google were being more strict or something. Cheers!

**Comment by riderx** [comment]
This has been done in production, the first 4 hours of your version people or bot from Google datacenter don't receive the update.
