### ISSUE TITLE
Need download/update progress

### ISSUE THREAD

**Issue by OFK0** [Cap-go/capacitor-updater#12]
Hi, thank u for awesome project

I know Just package has asyncProgressHandler for HTTP requests. Maybe that can provide progress event for us.

![resim](https://user-images.githubusercontent.com/28747412/154024863-e50d7341-06df-4122-b0ef-b3838af46b2d.png)
https://justhttp.github.io/

I thought there might be people like me who want to show the current progress as a percentage to users.

Best regards

**Comment by riderx** [comment]
Thanks for the idea, I didn't put download event for now because Apple don't look very happy about that.
But I will check again the rule to see what we can do :)

**Comment by lincolnthree** [comment]
@riderx I think there are valid internal / undisplayed uses for progress reporting (such as preventing too much network traffic at the same time while the app is in-use, and I can think of others.) So I think this feature is still useful, while I agree displaying progress visually is not a good idea.

**Comment by riderx** [comment]
@lincolnthree agree, i will put on roadmap to add it with a big warning in the documentation ^^

**Comment by OFK0** [comment]
Yay! :)

**Comment by riderx** [comment]
@lincolnthree @OFK0 the download event is out in `v1.4.1` 
check the doc here :
https://github.com/Cap-go/capacitor-updater#listen-to-download-events

**Comment by brice-noowu** [comment]
Thank you for your life saving work !

**Comment by OFK0** [comment]
@riderx it's working thanks :)
