### ISSUE TITLE
Variable value typo

### ISSUE THREAD

**Issue by roboxdev** [Cap-go/capacitor-updater#120]
https://github.com/Cap-go/capacitor-updater/search?q=donwloading

Expected / Actual value:
`downloading`
`donwloading`

<img width="768" alt="image" src="https://user-images.githubusercontent.com/5963980/202398755-9544782e-87a9-418b-8808-d1704b510544.png">

**Comment by riderx** [comment]
Thanks a lot i fixed it :)
