### ISSUE TITLE
[Android] Missing CRC32 response needed for self-host server

### ISSUE THREAD

**Issue by Kaizer69** [Cap-go/capacitor-updater#137]
[Here the guide](https://docs.capgo.app/self-hosted/auto-update/update-endpoint)
You must add CRC, else update and app crash on android

**Comment by riderx** [comment]
i'm not sure to understand, you talk about the sign hey ?

**Comment by Kaizer69** [comment]
No, when you put update on self-hosted server, you should put also crc in response
`return {
      version: '1.0.1',
      url: 'https://apiurl.com/mybuild_101.zip',
      **crc: 'xxxxxxx',**
    }`

The bug is [CapacitorUpdater.java#L324](https://github.com/Cap-go/capacitor-updater/blob/main/android/src/main/java/ee/forgr/capacitor_updater/CapacitorUpdater.java#L324)

`if (!checksumRes.equals("") && !checksumRes.equals(checksum)) {`

If checksum is missing, **checksumRes** will be null and will throw an exception.
Some ways to fix:
- check for checksumRes is nothing
- skip checksum if is missing in returned json

**Comment by riderx** [comment]
check the last version i made a fix for that
