### ISSUE TITLE
[Android] 404 on self hosted server

### ISSUE THREAD

**Issue by Kaizer69** [Cap-go/capacitor-updater#138]
Hello! If for some strange reason (error on CI/CD), the bundled zip in selfhosted server is missing, you can get a 404 response.
If capacitorupdate do a request to that address and get a HTTP 404, app will be crash!
You should trap exception and do a rollback of the latest version available on device.

Cheers

**Comment by riderx** [comment]
Oh interesting, i will check that, it shouldn't crash

**Comment by Kaizer69** [comment]
Android.
If i remember correctly, the problem is here [CapacitorUpdater.java#L303](https://github.com/Cap-go/capacitor-updater/blob/main/android/src/main/java/ee/forgr/capacitor_updater/CapacitorUpdater.java#L303)

`final File downloaded = new File(this.documentsDir, dest);`

If the response is 404, variable **dest** will be null and exception will be thrown. The exception is trapped, but next routines will crash the app.

**Comment by riderx** [comment]
Thanks for the report can you check the last version, i did release one to fix it
