### ISSUE TITLE
Issue Setting production to default

### ISSUE THREAD

**Issue by Zeusmist** [Cap-go/capacitor-updater#141]
Hi.
I get this error message after I run
`npx @capgo/cli@latest set -c production -s default`
![image](https://user-images.githubusercontent.com/51177741/209973357-b065971d-4c7f-40a0-ae53-2f07d106bdbc.png)

Before that, I first ran `npx @capgo/cli@latest upload -c production`

I am following instructions from this blog post [](https://capgo.app/blog/update-your-capacitor-apps-seamlessly-using-capacitor-updater/)

**Comment by riderx** [comment]
thanks for the report i will check that issue

**Comment by riderx** [comment]
so that linked to your other issue i believe, are you in the discord ? if yes please send me your email there

**Comment by riderx** [comment]
Found your bug! CLI `2.4.3` fix your issue !
