### ISSUE TITLE
Access to finishDownload or implementation

### ISSUE THREAD

**Issue by DinosaurDad** [Cap-go/capacitor-updater#146]
`finishDownload` isn't exposed via the plugin, so I tried to subclass the plugin. Unfortunately, `implementation` is private. Any chance you can make it protected to allow subclassing your plugin?

**Comment by DinosaurDad** [comment]
Nevermind, I needed a few things to be elevated from private to protected/public. I'll just work with my fork.

**Comment by riderx** [comment]
Hey @DinosaurDad I will be happy to make them protected/public, can you explain my your usecase?

**Comment by DinosaurDad** [comment]
That would be great. Because of limitations in the web view, there are some resources that need to be written to our "site" directory. Naturally, this can't be done with the public assets that are built into an apk/app. So rather than using _builtin_, we need the site to be started from writeable storage, even on first use.

We solved this by creating a stub site that would technically be _builtin_, but it never gets used. The app assets instead include a _starter.zip_ that contains the real site, built and zipped. This is extracted to writeable storage, and used for first launch. We added an `autoExtractStarter` config option that triggers the extraction in an override of `onActivityStarted` if your versions directory doesn't exist yet.

The upgraded access we need ended up being:

## CapacitorUpdater.java
```
  public void saveBundleInfo(final String id, final BundleInfo info) { ... }
```

## CapacitorUpdaterPlugin.java:
```
  protected CapacitorUpdater implementation;
```

We'll probably need something similar on iOS but we haven't started on an iOS version of our app yet.

Thanks!

![Updater Extension](https://user-images.githubusercontent.com/523433/211846168-db101ac2-f265-46d2-87db-dc65af7cf331.png)

**Comment by riderx** [comment]
How I'm sorry I never read your answer !
Can you share the code of what you did ?
I think it can be super useful for all users since some have also struggled with too big update, and we search for a solution to send update without certain assets.
This could be the base of a solution

**Comment by DinosaurDad** [comment]
I will try to clean up my approach to be a little more general purpose; I cut some corners for the specific needs in our app. I still need to give it a way to automatically re-extract the starter after a new .app is installed.
