### ISSUE TITLE
[BUG] - POST body doesnt being sent to server

### ISSUE THREAD

**Issue by Bokitza** [Cap-go/capacitor-updater#150]
1. using capacitor 4.6.1
2. using update 4.16.1
3. added the config to the ts file:   
` CapacitorUpdater: {
      updateUrl: "http://127.0.0.1:1337/api/update",
    }
`
4. the POST request DOES get to the server, yet no body is being sent, as described in the docs. :O
<img width="461" alt="image" src="https://user-images.githubusercontent.com/58147254/213890409-75ed5ec6-e8d8-40d6-8e81-bf0297f4ab41.png">

take notice that user agent grasps data about the app, but there is no body :/

**Comment by riderx** [comment]
Hello, that seems odd to me, are you sure your localhost is accessible from your device ?

**Comment by Bokitza** [comment]
It is, and I get the call on the local hosted server, just no body.

But I'm updating -this happens only on localhost!

On staging everything looks awesome

Maybe http related?

**Comment by riderx** [comment]
oh no, sorry it's a security feature in android  you cannot call http inside capacitor you need to allow it https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted

**Comment by Bokitza** [comment]
Ah cool thank you- maybe worth saying that in the documentation?

Cheers anyhow great app

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by riderx** [comment]
good point i will update it
