### ISSUE TITLE
android: error when finishing download

### ISSUE THREAD

**Issue by luantrasel** [Cap-go/capacitor-updater#153]
I'm testing the tool and I faced an issue when testing it on Android.

Debugging it I noticed that the error was because on [this line](https://github.com/Cap-go/capacitor-updater/blob/aa721cd9571489752f0e97187cadcc29c1fff8e9/android/src/main/java/ee/forgr/capacitor_updater/CapacitorUpdater.java#L466) the ivSessionKey is null so it was throwing an error

The error stacktrace:

> Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at ee.forgr.capacitor_updater.CapacitorUpdater.decryptFile(CapacitorUpdater.java:466)
        at ee.forgr.capacitor_updater.CapacitorUpdater.finishDownload(CapacitorUpdater.java:321)
        at ee.forgr.capacitor_updater.CapacitorUpdater$2.onReceive(CapacitorUpdater.java:296)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_54380(LoadedApk.java:1355)

I fixed it manually by adding an empty string as default on [this line](https://github.com/Cap-go/capacitor-updater/blob/aa721cd9571489752f0e97187cadcc29c1fff8e9/android/src/main/java/ee/forgr/capacitor_updater/CapacitorUpdater.java#L268)
`String sessionKey = bundle.getString(DownloadService.SESSIONKEY, "");`

Not sure if I did something wrong or if it is a bug and I fixed it correctly, but my problem was solved and then the version was downloaded correctly. Everything seems to work besides that. But maybe you could fix it? I didn't open a PR because as said I'm not sure if my fix is correct

**Comment by riderx** [comment]
thanks for the report, i think you are right, you can do the PR i merge it:)

**Comment by riderx** [comment]
fixed
