### ISSUE TITLE
Explanatoin

### ISSUE THREAD

**Issue by meilechwieder** [Cap-go/capacitor-updater#16]
Hi!

How will this work? if I set the update url is mywebsite.com/dist.zip, will download the zip every time app goes to background? how will it know if the zip has updates?

**Comment by riderx** [comment]
hello @meilechwieder if you use the download method who is `manual` mode, you have to manage all by yourself. 
So you have to check on your side if your app is already at the last version by saving it somewhere like in local storage.
If that too much work i recommend you to use the autoUpdate system who manage this for you.

**Comment by riderx** [comment]
@meilechwieder do you still need help ?
