### ISSUE TITLE
bug: Fix sonarcloud issues

### ISSUE THREAD

**Issue by riderx** [Cap-go/capacitor-updater#163]
Sonarcloud has a report of 59 issues.
The goal is to reduce that to 0 by or changing the code or explaining why it's safe.

**Comment by ujwalkumar1995** [comment]
Hey @riderx 
Do you mind sharing where we can see the list of issues?

**Comment by riderx** [comment]
sorry i thinked it was present in my message.
here you go:
https://sonarcloud.io/project/overview?id=Cap-go_capacitor-updater

**Comment by ujwalkumar1995** [comment]
@riderx 
Thank you. I will start working on this. Might not be able to complete all of the issues. Will try to resolve to the best of my capability.

**Comment by harishkadamudi** [comment]
@riderx , is this still open?

**Comment by riderx** [comment]
Yes

**Comment by pranjalg13** [comment]
@riderx can i work on this had raised a request earlier for the same, but somehow got deleted
Thanks

**Comment by pranjalg13** [comment]
Adding my attempt 
/attempt #164

**Comment by riderx** [comment]
or with npm command verify or with android studio and xcode, like any native project

**Comment by pranjalg13** [comment]
Hey @pbkompasz you can try this if you want, leaving the issue to you
Thanks

**Comment by rishi-raj-jain** [comment]
I see no one working on this actively, /attempt #163

**Comment by archie9211** [comment]
@riderx  Just wanted to know if this issue is still open to work and claim bounty. Thank you

**Comment by ologbonowiwi** [comment]
Hey folks! Since we're not having any activity here, I'm attempting this

/attempt #163

**Comment by ologbonowiwi** [comment]
Can you review #289 @riderx?

The variable name rule is the only rule that makes more sense to disable.

`CONSTANT_NAME` is a convention to most languages we use; that said, ignoring the Swift community convention rather than the cap-go convention here makes more sense.

If you find anything that needs to be changed on my PR, let me know :smile:

**Comment by KumarNayan** [comment]
Is this bounty still open ?  I see 64 code smells.

**Comment by riderx** [comment]
will not do for now

**Comment by ologbonowiwi** [comment]
Hey @riderx, I've put considerable effort into #289; I'd appreciate a tip for my work there.

**Comment by riderx** [comment]
You are right sorry i couldn't merge it
