### ISSUE TITLE
bug: ISO8601DateFormatter doesn't parse ISO date string

### ISSUE THREAD

**Issue by PawelPlutaUek20** [Cap-go/capacitor-updater#167]
https://github.com/Cap-go/capacitor-updater/blob/main/ios/Plugin/CapacitorUpdaterPlugin.swift#L393

formatter.formatOptions =  [.withInternetDateTime, .withFractionalSeconds]

https://stackoverflow.com/questions/41847672/iso8601dateformatter-doesnt-parse-iso-date-string

**Comment by riderx** [comment]
Hey man thanks for that, can you do a PR it's a great fix
