### ISSUE TITLE
Property 'addListener' does not exist on type 'CapacitorUpdaterPlugin'

### ISSUE THREAD

**Issue by Kaizodo** [Cap-go/capacitor-updater#17]
```
 CapacitorUpdater.addListener('download', (info: any) => {
      console.log('download was fired', info.percent);
 });
```

Property 'addListener' does not exist on type 'CapacitorUpdaterPlugin'

**Comment by riderx** [comment]
it's fixed, can you try the v2.0.11 ?

**Comment by Kaizodo** [comment]
yes its working however download is failing don't know why

**Comment by Kaizodo** [comment]
![image](https://user-images.githubusercontent.com/55124640/159630616-87ec2c60-686e-47f7-9a67-392861fccda4.png)

**Comment by Kaizodo** [comment]
i am using http instead of https  could the reason ?
