### ISSUE TITLE
feat: allow same versions across different channels

### ISSUE THREAD

**Issue by MarianBe** [Cap-go/capacitor-updater#170]
## Feature Request
Allow for the same version codes across different channels
### Description

If we have a production and a staging channel, we can't have version `1.0.0` on both channels at the same time, which also means we will have to keep track of the latest version across our branches.
Our ideal workflow would be to allow us to create update-versions for PR-branches without really affecting the production-channel versions. 

### Preferred Solution

Have independent versioning across the branches

**Comment by riderx** [comment]
Hello @MarianBe can you explain a bit more ?
you can use the bundle code in channel as much as you want but you can't upload 2 bundle with the same version name.
To do so, you can use the semver recomendation.
`1.0.0` for your bundle prod env
`1.0.0-beta.1` for your dev env
`1.0.0-alpha.1` for your preprod env
Do that answer your question ?
