### ISSUE TITLE
Zip Download urls with HTTP are not working

### ISSUE THREAD

**Issue by Kaizodo** [Cap-go/capacitor-updater#18]
Bug confirmed zip downloads with http is failing and working perfectly with https

**Comment by riderx** [comment]
I don't think it's a bug of the plugin it's more something coming from OS security rules,
you can find a bit more about it there: https://stackoverflow.com/questions/51902629/how-to-allow-all-network-connection-types-http-and-https-in-android-9-pie
i will update the doc to let others know it's not possible without config in the app
