### ISSUE TITLE
Wrong download percentage 

### ISSUE THREAD

**Issue by Kaizodo** [Cap-go/capacitor-updater#19]
![image](https://user-images.githubusercontent.com/55124640/159632644-9baaa272-4b47-485c-be89-8549ee6879e5.png)

**Comment by Kaizodo** [comment]
download size is 1.9 MB but i think after 99% its overlapping the percentage  somehow or miscalculating

**Comment by riderx** [comment]
@Kaizodo this in iOS or Android ?

**Comment by Kaizodo** [comment]
@riderx  its Android

**Comment by riderx** [comment]
Thanks i will have a check :)

**Comment by Kaizodo** [comment]
thanks for the quick response issue seems to be resolved in this update
