### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Bokitza** [Cap-go/capacitor-updater#190]
### Capacitor Version
```
Latest Dependencies:
  @capacitor/cli: 4.7.3
  @capacitor/core: 4.7.3
  @capacitor/android: 4.7.3
  @capacitor/ios: 4.7.3

Installed Dependencies:
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/cli: 4.6.1
  @capacitor/ios: 4.6.1
```

### Plugin Version

```
 Installed Dependencies:
   @capgo/cli: 3.10.2
   @capgo/capacitor-updater: ^4.42.0

✓ Latest Dependencies:
   @capgo/cli: 3.10.2
   @capgo/capacitor-updater: 4.42.0

```

### Current Behavior

I tried a manual and an automatic self hosted solution, and I guess the version wont come through the commands.
examples:

the code
![image](https://user-images.githubusercontent.com/58147254/233089669-4d9eb8ee-a475-4534-bfe2-233dff2737e3.png)

the console on safari ios
![image](https://user-images.githubusercontent.com/58147254/233089815-fb6357c9-c645-480f-ab0b-c66f0831521a.png)

the error
![image](https://user-images.githubusercontent.com/58147254/233089872-7fecbf32-bb1f-4bf2-b457-8936c5dd99fd.png)

### Expected Behavior
the version to come from the server, and the app to update if its higher then current.

`npm --version` output: 7.10.0

`node --version` output: 16.0.0

`pod --version` output (iOS issues only): 1.11.3

**Comment by riderx** [comment]
Hey @Bokitza i think your forget to explain what was your bug ^^

**Comment by Bokitza** [comment]
omg i took so much effort in this issue and its just gone. second editing

**Comment by Bokitza** [comment]
snap it was commented out lol -there u go mate

**Comment by riderx** [comment]
Better now ! 
As you can see in your screenshot "the console on safari ios", there no version key in the option payload.
So the download function is refusing because of that.
What is weird is i can see in your console log just before the key exist ^^.
I have no explaination why the key is not passed.
Could you create a reproduction repo ?
