### ISSUE TITLE
bug: is_prod is allways false

### ISSUE THREAD

**Issue by Serra19** [Cap-go/capacitor-updater#191]
### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 4.7.3
  @capacitor/core: 4.7.3
  @capacitor/android: 4.7.3
  @capacitor/ios: 4.7.3

Installed Dependencies:

  @capacitor/android: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/ios: 4.3.0
  @capacitor/cli: 4.3.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Plugin Version

```
     💊   Capgo Doctor  💊

 OS: Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64

 Installed Dependencies:

   @capgo/cli: 3.10.2
   @capgo/capacitor-updater: ^4.42.0


✓ Latest Dependencies:


   @capgo/cli: 3.10.2
   @capgo/capacitor-updater: 4.42.0


🚨 Some dependencies are not up to date
```

### Platform(s)

iOs and I don't know if Android, I haven't tried it

### Current Behavior

I'm using this package with my own server and auto-update mode, and I'm always receiving is_prod = false with the production builds.

### Expected Behavior

On the production builds, I should receive is_prod = true

### Other Technical Details

`npm --version` output: 8.19.1

`node --version` output: v18.9.1

`pod --version` output (iOS issues only): 1.11.3

**Comment by riderx** [comment]
@Serra19 what do you mean by production build ?
production in capgo mean it's app store app not xcode app

**Comment by Serra19** [comment]
exactly, that's what I mean with production build

**Comment by riderx** [comment]
can you try the latest release and tell me if that fix ?

**Comment by Serra19** [comment]
Of course! I will try this week and tell you how it was.

With latest release, you mean npm one (4.44.0)? or Github one (4.47.0)?

btw, I guess testflight app is a production app, right?

Thank you! :)

**Comment by riderx** [comment]
hey, ok so the issue if there: testflight is not considerer as production only published on app store is

**Comment by riderx** [comment]
in fact we can, but since in Android we cannot (or i don't know how) i have align to android behavior

**Comment by Serra19** [comment]
I've tested on Android, and the internal testing versions are considered as production versions. Maybe this is because it is installed from Google Play Store, but it is the testflight equivalent for Android.

What I'm trying is to avoid capacitor-updater downloading new versions when I'm developing and testing in dev mode.

Do you have any solution for this? I guess I'm missing something, but I don't know how to do that... 😓 

Thank you for your help!

**Comment by Serra19** [comment]
Ok, I think I see how to manage it.

Thank you very much for your help and for developing this amazing plugin! :)
