### ISSUE TITLE
bug: isMainActivity Method is Not Null Safe (Android)

### ISSUE THREAD

**Issue by danbunkr** [Cap-go/capacitor-updater#192]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.7.3
  @capacitor/core: 4.7.3
  @capacitor/android: 4.7.3
  @capacitor/ios: 4.7.3

Installed Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.7.1
  @capacitor/android: 4.7.1
  @capacitor/ios: 4.7.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
➜  bunkr-client git:(master) ✗
```

### Plugin Version

```
"@capgo/capacitor-updater": "4.17.37",
```

### Platform(s)

Android

### Current Behavior

We have a bit of a weird situation where this plugin and another plugin are conflicting. We have written a custom plugin that has been open sourced - https://github.com/carsten-klaffke/send-intent. This plugin allows users to share data into a capacitor application via the share sheet. For Android what we do is start a new intent with the application running and this passes the data into it. From there the user can share the data within the app and after the data is shared we call `finish()` at the Android native level which closes the intent. This is expected behavior for Android activity intents. However, if the app was hard closed prior to the intent happening when we hit finish the Capacitor Updater platform errors out and crashes the app which gets presented to the user.

See more details on the error below

![image](https://user-images.githubusercontent.com/82471930/233482478-e6631d09-4e30-4f40-91aa-31b810b7ac27.png)

### Expected Behavior

See the next line but we should gracefully handle null conditions without crashing the entire application.

### Code Reproduction

It would be a bit hard to reproduce but I can follow up with you in discord if need be. But really the fix would be for the `isMainActivity` method in Android part of the plugin to gracefully handle null conditions for the issue above.

### New Section - Potential Solution

Right now the method that is erroring is as follows:

```
  private boolean isMainActivity() {
    Context mContext = this.getContext();
    ActivityManager activityManager =
      (ActivityManager) mContext.getSystemService(Context.ACTIVITY_SERVICE);
    List<ActivityManager.AppTask> runningTasks = activityManager.getAppTasks();
    ActivityManager.RecentTaskInfo runningTask = runningTasks
      .get(0)
      .getTaskInfo();
    String className = runningTask.baseIntent.getComponent().getClassName();
    String runningActivity = runningTask.topActivity.getClassName();
    boolean isThisAppActivity = className.equals(runningActivity);
    return isThisAppActivity;
  }
  ```
  
  Handling the null safe conditions like so could potentially fix: (Note I am not a java developer and dont know Android but used chatGPT to offer this suggestion... im assuming it could be improved upon but wanted to provide something at-least)  
  
  ```
  private boolean isMainActivity() {
    Context mContext = this.getContext();
    if (mContext == null) {
        return false;
    }
    ActivityManager activityManager =
      (ActivityManager) mContext.getSystemService(Context.ACTIVITY_SERVICE);
    if (activityManager == null) {
        return false;
    }
    List<ActivityManager.AppTask> runningTasks = activityManager.getAppTasks();
    if (runningTasks == null || runningTasks.isEmpty()) {
        return false;
    }
    ActivityManager.RecentTaskInfo runningTask = runningTasks
      .get(0)
      .getTaskInfo();
    if (runningTask == null) {
        return false;
    }
    Intent baseIntent = runningTask.baseIntent;
    if (baseIntent == null) {
        return false;
    }
    ComponentName component = baseIntent.getComponent();
    if (component == null) {
        return false;
    }
    String className = component.getClassName();
    if (className == null) {
        return false;
    }
    String runningActivity = runningTask.topActivity.getClassName();
    if (runningActivity == null) {
        return false;
    }
    boolean isThisAppActivity = className.equals(runningActivity);
    mContext = null;
    return isThisAppActivity;
}
```

**Comment by riderx** [comment]
Thanks for the report:
i tried to add a try catch around the code tell me with the latest one that help or not
