### ISSUE TITLE
bug: Changelog is wrong

### ISSUE THREAD

**Issue by arendjantetteroo** [Cap-go/capacitor-updater#202]
You are probably aware already, but the changelog you publish with each release is getting longer and longer and it's totally unclear what has changed in each version. 

This makes it rather hard to know if it's time to upgrade to a newer release or we can stay on the current release. 

Is there more information on the Breaking changes in one of the later releases, and how to migrate our code to support the new version?

**Comment by arendjantetteroo** [comment]
I also saw that v5 and v6 are not on npm, is that correct?

**Comment by riderx** [comment]
yes because they are wrong, i have found a fix in local for the changelog but the CI still do the stupid bump from 3 months. i'm on it

**Comment by riderx** [comment]
Should be good now, I finally found the mystery!
