### ISSUE TITLE
bug: Manual mode not reverting

### ISSUE THREAD

**Issue by co-dax** [Cap-go/capacitor-updater#209]
Version 10.0.0, android, manual mode not reverting to previous version when `CapacitorUpdater.notifyAppReady()` is not called.

If I do two updates with the same zip bundle that is not calling `CapacitorUpdater.notifyAppReady()` then it is not reverting on the first update but on the second update with the same zip bundle (that is not calling `CapacitorUpdater.notifyAppReady()`) then it does revert but twice in a row thus getting back to builtin version.

**Comment by co-dax** [comment]
It turns out it was not reverting since I had called `CapacitorUpdater.notifyAppReady()` after `CapacitorUpdater.set(...)`. `CapacitorUpdater.set(...)` is setting the downloaded new version and is also immediately reloading the web view but it is not stopping the code execution thus `CapacitorUpdater.notifyAppReady()` is called and by doing so it marks the newly downloaded version as ok from the old code. When the web view finishes reloading then it will not revert to the previsou version even if the new version is not calling `CapacitorUpdater.notifyAppReady()` because it was called above in the text by old code just after the call to `CapacitorUpdater.set(...)`.
Essentially `CapacitorUpdater.set(...)` is not stopping the code execution.

**Comment by riderx** [comment]
Thanks for sharing that i will link that to the doc
