### ISSUE TITLE
No clear error message when download fails

### ISSUE THREAD

**Issue by snimavat** [Cap-go/capacitor-updater#21]
When zip download fails for some reason, the plugin just outputs the error "Download failed" Without any clear message / error on what went wrong or why download has failed. Not helpful for debugging / investigating the issue

**Comment by Kaizodo** [comment]
Make sure your zip file url is HTTPS

**Comment by riderx** [comment]
Thanks for the feedback, it's added in the roadmap!
<img width="301" alt="Screenshot 2022-04-05 at 12 30 02" src="https://user-images.githubusercontent.com/4084527/161744609-30fa90dd-6d41-4b33-87e3-3e50e23f4ca4.png">

**Comment by PIXPOINT** [comment]
Haven't used the plugin for a while because it doesn't work optimally under iOS. Today I wanted to start a new insurance and I also get the message "download failed" in Android, but unfortunately there is no exact description.
The direct download of the file works, but an error message appears via the `CapacitorUpdater.download` function.

**Comment by doublechecker** [comment]
First of all. Nice plugin! Thanks for this!.


We have exactly the same issue. In the beginning it worked but sometimes the message "Capacitor-updater: download unzip error" comes up and i don't know what went wrong. What failed? The download or the unzipping?

I saw that you use SSZipArchive (https://github.com/Cap-go/capacitor-updater/blob/main/ios/Plugin/CapacitorUpdater.swift#L134). There are some method overloads where you could get error information. I guess this would help quite a lot.

**Comment by riderx** [comment]
Hey guys it has been updated in v4, can you upgrade and check. ?

**Comment by PIXPOINT** [comment]
Perfect, that worked! The dashboard creation works now, thanks for the help 😀
