### ISSUE TITLE
bug: Exception not thrown when bundle downloading error occurs

### ISSUE THREAD

**Issue by co-dax** [Cap-go/capacitor-updater#210]
## Bug Report

iOS, manual mode, as instructed by @riderx function `CapacitorUpdater.download(...)` is supposed to throw an exception when a downloading error occurs (for example bad network) but this is not happening on iOS. It does work as expected on Android.

### Capacitor Version
5.0.0

### Plugin Version
5.0.1

### Platform(s)
iOS

### Current Behavior
function `CapacitorUpdater.download(...)` is not throwing an exception when a downloading error occurs (for example bad network) but this is not happening on iOS. 

### Expected Behavior
function `CapacitorUpdater.download(...)` is supposed to throw an exception when a downloading error occurs (for example bad network) but this is not happening on iOS. 

### Additional Context
It works as expected on Android.

**Comment by riderx** [comment]
Thanks a lot i will have a check asap

**Comment by riderx** [comment]
Thanks! i will look at it

**Comment by riderx** [comment]
After deeper talk we found the issue come from the tool who compress who do something that java doesn't understand.
The good part is that doesn't happen if you use the Capgo CLI.
`npx @capgo/cli@latest zip BUILD_FOLDER`
where BUILD_FOLDER is the path to your build folder

**Comment by co-dax** [comment]
Thanks @Martin but the error was not being thrown when I turn off network connection half way though the download process.

**Comment by forgr-owner** [comment]
You mean that different one?

**Comment by riderx** [comment]
https://capgo.app/docs/plugin/know-issues/#unzip

**Comment by co-dax** [comment]
This issue is not related to [https://capgo.app/docs/plugin/know-issues/#unzip](https://capgo.app/docs/plugin/know-issues/#unzip). 
It is a separete issue when the exception is not being thrown when you turn off network access on an iOS mobile device while capacitor-updater is downloading update zip bundle file.

**Comment by riderx** [comment]
oh okay

**Comment by co-dax** [comment]
@riderx I have just tested and I can confirm it does fire the even when an exception occurrs when I turn the network off half way through the download process which should correspond to bad/unstable network.
Thanks.

**Comment by co-dax** [comment]
@riderx ...but now it is started asking for network permissions the first time the plugin tries to download the zip file and it also causes an exception (the exception that you have introduced with your change from above with the version [5.3.36](https://github.com/Cap-go/capacitor-updater/tree/5.3.36)) before asking for network permissions causing the update to fail. The next updates work fine though.


So the problem is that it is asking for permissions but it does not wait for permissions grant and it rather throws an exception.

Strange that it is asking for network permissions all of a sudden since this was not the case until now.

**Comment by co-dax** [comment]
@riderx it seems that it is only asking for network permissions if the zip file is being downloaded from **local** network which is what I was doing while developing. I tried proving zip url that is pointing to an external path and it just worked fine.
It be the case to handle that situation or otherwise just update the docs since it is only an issue with local/development environment.

**Comment by riderx** [comment]
It's now in the doc, thanks
