### ISSUE TITLE
Updating from a private GitHub repository

### ISSUE THREAD

**Issue by ManuLpz4** [Cap-go/capacitor-updater#215]
Hey, how is it going?

I'm downloading the asset from a release in my private repository and that breaks because the download cant start because the asset is private BUT maybe I can get the final url of the asset (with axios or something) OR downloading with octokit and later in CapacitorUpdater.download put the local file downloaded.

Any suggestion?

```ts
const { data: latestRelease } = await octokit.request(
    "GET /repos/{owner}/{repo}/releases/latest",
);
const downloadUrl = latestRelease.assets.find((asset: any) => (asset.name = "dist.zip"))?.browser_download_url;
// ...
await CapacitorUpdater.download({
    url: downloadUrl,
    version: nextVersion,
});
```

**Comment by ManuLpz4** [comment]
Solution:

```ts
const { url: downloadUrl } = await octokit.request(
        `GET /repos/${org/${repo}/releases/assets/${latestRelease.assets[0].id}`,
);
```

**Comment by ManuLpz4** [comment]
New error 😭
<img width="632" alt="Captura de pantalla 2023-06-13 a la(s) 15 53 32" src="https://github.com/Cap-go/capacitor-updater/assets/17878459/1b02c546-d09d-47ae-9689-26bce4aee8ed">

**Comment by riderx** [comment]
@ManuLpz4 this is not linked to the updater just to your way of doing it. you  can host them in public somewhere and use encryption to be sure no one can read them.
