### ISSUE TITLE
bug: Unable to use this plugin, please help

### ISSUE THREAD

**Issue by qingshuiling** [Cap-go/capacitor-updater#216]
Uncaught (in promise)  {"name": "Error", "message": ""CapacitorUpdater" plugin is not implemented on android", "stack": "Error: "CapacitorUpdater" plugin is not implemented on android\n    at p (https://localhost/js/chunk-vendors.4edb939d.js:3:2260)\n    at https://localhost/js/chunk-vendors.4edb939d.js:3:2714"}

After making android, it will prompt this error, which is very difficult.

**Comment by riderx** [comment]
hello do you installer the plugin with a sync ?
