### ISSUE TITLE
Disable sending usage statistics

### ISSUE THREAD

**Issue by manu2311** [Cap-go/capacitor-updater#22]
Hi,

since version 1.3.0 usage stats are sent to cappgo. The documentation says that I can change this behaviour to send usage stats to a custom server. But I don't want to send any usage stats. Is there a possibility to disable sending usage stats at all? From some tests I think configuring an empty string as statsUrl does the job, but I'm not sure whether this is the correct way/intended behaviour because the docs don't say anythin about this.

**Comment by riderx** [comment]
Hello @manu2311, 
Thanks for asking, you're doing all right, empty string stop the stat feature.
I updated the doc to make it crystal clear!

Can I ask you why you want to stop anonymous statistics, to help me improve it ?

I made it super privacy-friendly with anonymous UUID, just to allow me to understand problems and usage as much as i can.

I thought it will be okay like that :)

**Comment by manu2311** [comment]
Hi @riderx,

Thanks for the clarification. I understand your intention of the stats, but from my understanding I have to add information to my data protection section of the app even if the usage data is anonymous. Moreover the user cannot opt-out of sending usage data. Maybe this could be a new feature to enable or disable the usage data by code so that the user can choose?

**Comment by riderx** [comment]
@manu2311 yes you are right, i will add to the roadmap this evolution
