### ISSUE TITLE
bug: app size getting bigger on update in ios 

### ISSUE THREAD

**Issue by madhumurugan89** [Cap-go/capacitor-updater#224]
### Capacitor Version

```

Latest Dependencies:
@capacitor/cli: 5.1.0
@capacitor/core: 5.1.0
@capacitor/android: 5.1.0
@capacitor/i05: 5.1.0
Installed Dependencies:
@capacitor/ios: 4.8.1
@capacitor/android: 4.8.1
@capacitor/core: 4.8.1
@capacitor/cli: 4.8.1

```

### Plugin Version

```

Capgo Doctor
05: Windows
10 Pro
Installed Dependencies:
@capgo/cli:
3.12.1 @capgo/capacitor-updater:
^4.35.0
Some dependencies are not up to date

```

### context(s)

```md
ManualModel: true
AutoMode: false
CapgoCloud: false
OnPremise: true
```

### Platform(s)
ios

### Current Behavior
In Ios on app update, the size of the application is getting bigger in storage. On each update the size is increasing. 

The delete bundle method is not working in IOS. 

Android doesn’t have this issue. App size is not increasing

### Expected Behavior
On app update the previous bundles should be deleted from storage. This is only for Ios

**Comment by riderx** [comment]
Thanks for the report i will look into this !

**Comment by madhumurugan89** [comment]
Thanks @riderx

**Comment by riderx** [comment]
@madhumurugan89 i cannot reproduce can you share your xcode logs :
you should find this "Failed to delete previous bundle" if there an issue

**Comment by madhumurugan89** [comment]
Thanks for the reply. The issue can be reproduced with below steps.
I I am using self hosted option to update the app.
Steps:
Install the App
1. Check Initial app size from app settings, , the app size is 50 MB
2. After First update = 75 MB (update zip size will be 25MB)
3. After second Update = 100MB
4. third update = 125 MB
With each update the app size is increasing. The delete bundle is not happer
for ios. In android this issue is not there.

**Comment by riderx** [comment]
@madhumurugan89 I just saw in your doctor command you use the updater V3, while been with capacitor v5 why ?
V3 is not maintained and not compatible with Capacitor v5.
Please upgrade and see if than fix your issue.
