### ISSUE TITLE
Unable to capacitor sync on iOS

### ISSUE THREAD

**Issue by berkayyildiz** [Cap-go/capacitor-updater#23]
Hello when I tried to run cap sync I get this error. It only happens when this package installed. Is there anyone that have any idea?

```
✖ Updating iOS native dependencies with pod install - failed!
✖ update ios - failed!
[error] Ignoring ffi-1.15.0 because its extensions are not built. Try: gem pristine ffi --version 1.15.0
        Analyzing dependencies
        objc[25636]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib
        (0x1efa1f130) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice
        (0x1065202c8). One of the two will be used. Which one is undefined.
        objc[25636]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x1efa1f180) and
        /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x106520318).
        One of the two will be used. Which one is undefined.
```

**Comment by riderx** [comment]
Hello, i never see this error, could you share your capacitor, x-code and cocoapod version?

**Comment by riderx** [comment]
@berkayyildiz  ?

**Comment by OFK0** [comment]
@riderx i think the reason is not this package
@berkayyildiz Selam Berkay, bu hata çıktısı capacitor-updater ile alakalı değil gibi hissettim.
`gem pristine ffi --version 1.15.0` yapmayı denedin mi?

Hello Berkay,
In my opinion, the errors reason is not capacitor-updater package. 
Have you been tried `gem pristine ffi --version 1.15.0` before?

**Comment by riderx** [comment]
ok thanks, i close it for now if that related feel free to open a new one

**Comment by berkayyildiz** [comment]
Sorry for being late. Thanks @OFK0 I actually tried too that but I got another error after it and I leaved it like that. I finally figured it out the issue. Apparently M1 macs' architecture was creating problem. `sudo arch -x86_64 gem install ffi` Running install with prefix fixed the problem.  I'm leaving it here in case it happens to anyone.
