### ISSUE TITLE
feat: setChannel to trigger checking for an update

### ISSUE THREAD

**Issue by simon-acuitymd** [Cap-go/capacitor-updater#231]
### Description
When you call setChannel, you likely want to check if there are any pending bundles for that channel and get an update. Right now you can either use manual mode API calls and string together a download, or you can reopen the app to trigger fetching a new bundle and then the user has to reload the app again.

It would be nice if `setChannel` had an option to trigger checking for & downloading new bundles. The pattern I would then be able to use is:
1. Set up update listener
2. Set channel
3. Respond to update event in the listener by reloading the view

### Platform(s)
All? I'm on ios but presumably this is useful for all platforms.

### Preferred Solution
Mentioned in the description.

**Comment by WcaleNieWolny** [comment]
Is calling `getLatest()` not enough?

**Comment by riderx** [comment]
Some user want it more simple.
Like setchannel do the getLatest and the set all at once

**Comment by WcaleNieWolny** [comment]
How would I go about actually testing my changes? I believe I can test this on android as I run linux but writing code on macos would not be possible for me. How do I go about implementing this in IOS?

**Comment by riderx** [comment]
On ios that will be hard if you don't have a mac, maybe you can use a vm but not sure it will be convenient

**Comment by WcaleNieWolny** [comment]
I will do my best with the android feature for now. It could serve as a reference impl for somebody to implement this on IOS. Will that work?

**Comment by WcaleNieWolny** [comment]
I will probably not submit a PR for this until tomorrow or the day after that as I do have to properly setup my environment

**Comment by riderx** [comment]
I think i can help on IOS part
