### ISSUE TITLE
Better documentation for start the project in local

### ISSUE THREAD

**Issue by riderx** [Cap-go/capacitor-updater#238]
Currently starting the project is buggy with the latest Supabase change so the goal is to upgrade the db migration to fix it and update the doc if needed.

**Comment by tungpham-dev** [comment]
Hi @riderx! I've opened a PR adding a LOCAL_DEVELOPMENT.md guide covering the updated Supabase migration steps and full local setup. This addresses the Supabase CLI changes mentioned in the issue. Happy to revise anything!
