### ISSUE TITLE
bug: Angular app not loading after update (iOS)

### ISSUE THREAD

**Issue by MichaelMaenner** [Cap-go/capacitor-updater#245]
### Capacitor Version

```
  @capacitor/cli: 4.3.0
  @capacitor/core: 4.2.0
  @capacitor/android: 4.2.0
  @capacitor/ios: 4.2.0
```

### Plugin Version

```
   @capgo/cli: 3.13.5
   @capgo/capacitor-updater: ^4.61.10
```

### context(s)

```md
ManualModel: true
AutoMode: false 
CapgoCloud: false
OnPremise: true
```

### Platform(s)

- iOS

### Current Behavior

After we installed the first update, the app remains white and does not load.

### Expected Behavior

 
After we have installed the first update the application should load (works on android)

### Other Technical Details

`npm --version` output: `9.5.1`

`node --version` output: `v18.16.0`

`pod --version` output (iOS issues only): `1.11.3`

### Additional Context

We have an Angular application that checks the app version every time it is started and updates the app if necessary. 
This works fine on Android. The app restarts after the update and displays the new content.
This also works on the iOS simulator.
Unfortunately, this problem only occurs with native iOS devices.

If we manually close and reopen the app, the correct (updated) content is displayed.
The log output shows no errors and even confirms that the new package was successfully loaded.

Only the Angular application no longer loads properly after the update..
The `index.html` loads and displays the updated content. 
But after that, the app stops working (app doesn't crash or freeze).
Only angular doesn't work properly after that.

**Comment by riderx** [comment]
Can you create a reproduction repo ?

**Comment by MichaelMaenner** [comment]
I will try to provide you with a reproduction repo asap. But this might take a week or two.

**Comment by MichaelMaenner** [comment]
Unfortunately, I am unable to recreate the problem in a new repo. 
Looks like the problem is on our side.
If I can somehow reproduce the issue, I will reopen the issue or create a new one.
