### ISSUE TITLE
feat: Configure the channel in capacitor.config.json

### ISSUE THREAD

**Issue by luisbytes** [Cap-go/capacitor-updater#248]
### Description

It would be advisable to set up the channel within the capacitor.config.json file, considering the scenario described below in a hypothetical case where environment variables exist in different environments (prod and dev). To address this, two types of APKs are generated (dev and prod). If there isn't a way to assign the channel during the creation of the prod APK and we are in auto-update mode, the update corresponding to the default channel might be downloaded, which in this example could be "dev". However, this is not ideal, as the bundle zip generated and associated with dev doesn't contain the same variables as prod.

### Platform(s)

- Android
- iOS

### Preferred Solution

```
const config: CapacitorConfig = {
  plugins: {
    CapacitorUpdater: {
      channel: 'production'
    }
  }
};
```

Based on that channel specified in the API for fetching updates, it knows which channel to search in. This way, the user wouldn't inadvertently download development updates first and then production updates `(assuming we use `.setChannel('production')` in our app's logic)`.

**Comment by riderx** [comment]
Done check : https://github.com/Cap-go/capacitor-updater/issues/304
