### ISSUE TITLE
bug: failed download because of checksum

### ISSUE THREAD

**Issue by khamaileon** [Cap-go/capacitor-updater#273]
## Bug Report

The "download" command doesn't seem to save the bundle on the phone. When I list the bundles, it's empty and when I run the "set" command, I get an error saying that the bundle id doesn't exist. Am I missing something?

![271275172-9a36059d-543a-464b-8e03-8938b8f06ddb](https://github.com/Cap-go/capacitor-updater/assets/1322166/3d2552a6-e66a-425f-b8b3-b529f600ee3e)

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.4.1
  @capacitor/core: 5.4.1
  @capacitor/android: 5.4.1
  @capacitor/ios: 5.4.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/core: 5.4.1
  @capacitor/android: 5.4.1
  @capacitor/cli: 5.4.1
```

### Plugin Version

```
 OS: #180-Ubuntu SMP Tue Sep 5 13:21:23 UTC 2023

 Installed Dependencies:

   @capgo/cli: 3.14.1
   @capgo/capacitor-updater: ^5.2.35
```

### context(s)

```md
ManualModel: true
AutoMode: false
CapgoCloud: false
OnPremise: false
```

### Code Reproduction

```javascript
  methods: {
    async checkForUpdates() {
      const bundles = await CapacitorUpdater.list();
      console.log(bundles);
      const currentBundleInfo = await CapacitorUpdater.current();
      console.log("Current version: " + currentBundleInfo.bundle.version);
      console.log("Native version: " + currentBundleInfo.native);
      const currentVersion =
        currentBundleInfo.bundle.version === "builtin"
          ? currentBundleInfo.native
          : currentBundleInfo.bundle.version;
      console.log("Current version: " + currentVersion);
      const latest = await fetch(
        "https://example.com/releases/latest.json"
      ).then((response) => response.json());
      console.log("Latest version: " + latest.version);
      if (currentVersion !== latest.version) {
        console.log("Downloading update");
        const bundle = await CapacitorUpdater.download({
          url: latest.url,
          version: latest.version,
          checksum: latest.checksum,
        });
        console.log(bundle);
        const bundles = await CapacitorUpdater.list();
        console.log(bundles);
        await CapacitorUpdater.set(bundle);
      }
    },
```

### Other Technical Details

`npm --version` output:

10.1.0

`node --version` output:

v20.7.0

`pod --version` output (iOS issues only):

**Comment by khamaileon** [comment]
After some investigation, I found that the problem comes with the checksum

![image](https://github.com/Cap-go/capacitor-updater/assets/1322166/4f70c151-fa14-4399-b7d8-a17a1fb9ad10)

The 2 strings are equal and yet there is an error.

Beyond that, I wonder why the JS promise of the download function isn't rejected?

**Comment by riderx** [comment]
Hello @khamaileon thanks for the report.
First thing first the log "Error checksum" was incorrect, I just read the code, and he was printing the same value 2 times.
I just modified it and pushed a new version.
How did you made the checksum ? Did you use Capgo CLI ?
I will check why it doesn't reject when checksum fail

**Comment by khamaileon** [comment]
Ok thanks I'll check again. Yes the checksum is from Capgo CLI

**Comment by khamaileon** [comment]
I did it with the latest version and it passes with the checksum. Thanks @riderx. BTW, I didn't check the reject in case of incorrect checksum.

**Comment by khamaileon** [comment]
I'm reopening this because I've got a checksum problem again. I haven't looked into the details yet, but I notice that the Promise of CapacitorUpdater.download is never rejected on error. It just stays stuck forever. @riderx: do you remember if this was fixed by you in the end?

**Comment by riderx** [comment]
Thanks for the report, i think it’s a different issue, but anyway what platform do you have the issue, what version ?

**Comment by khamaileon** [comment]
"@capgo/capacitor-updater": "^6.1.20",
"@capgo/cli": "4.14.16",

The problem right now is on Android. I haven't tested it on iOS yet. The Promise problem was mentioned in the thread. I thought it had been fixed.

As for the checksum, yes it does seem to be another issue. I'm struggling to pinpoint it. For the moment I can see that the bundle command doesn't give me the same checksum locally as in my CI. Has anything changed recently that could explain this?

**Comment by riderx** [comment]
It was but maybe latest change made a regression.
I will have look today.
Do you use encryption?
We made checksum a bit different in encryption V2, it shouldn’t affect you, maybe we have unexpected regression can you share the command you use to bundle ?

**Comment by khamaileon** [comment]
`pnpm exec capgo bundle zip --json`

After a big reset, it works again on my side. I can't explain why there was a checksum error. Maybe a cache problem somewhere. In any case, it would be nice to reject the Promise so that when this happens, the user doesn't get stuck.

**Comment by riderx** [comment]
I think I just found one exception that was not caught properly, so I improved it here: https://github.com/Cap-go/capacitor-updater/commit/4495a374ae712bed37e93ca64de27f87b42acb85

**Comment by khamaileon** [comment]
Okay, I've just tested it, it solves the problem. Thank you.
