### ISSUE TITLE
feat: disable stats

### ISSUE THREAD

**Issue by khamaileon** [Cap-go/capacitor-updater#274]
I have a custom installation of Capacitor Updater but apparently it still sends stats ( a lot ) to api.capgo.app/stats. How can I disable it?

By the way, can't we store this cookie once and for all?

![image](https://github.com/Cap-go/capacitor-updater/assets/1322166/5a3a3b00-1649-4066-a72a-ff557fb9f8eb)

**Comment by riderx** [comment]
hello if you don't use Capgo you can disable it by putting statsUrl: "" in capacitor config
https://capgo.app/docs/plugin/settings/#statsurl
There shouldn't be cookies at all, i will look to see how i can disable it

**Comment by khamaileon** [comment]
Great :+1:

**Comment by riderx** [comment]
i don't find anything in volley got about cookie

**Comment by riderx** [comment]
But if you disable stats cookie log will not be display
