### ISSUE TITLE
bug: getLatest returning old data

### ISSUE THREAD

**Issue by andreisaikouski** [Cap-go/capacitor-updater#279]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.4.2
  @capacitor/core: 5.4.2
  @capacitor/android: 5.4.2
  @capacitor/ios: 5.4.2

Installed Dependencies:

  @capacitor/cli: 5.2.3
  @capacitor/core: 5.2.3
  @capacitor/android: 5.2.3
  @capacitor/ios: 5.2.3

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Plugin Version

```
PASTE OUTPUT HERE
```

### context(s)

```md
ManualModel: true
AutoMode: false
CapgoCloud: false
OnPremise: false
```

Self hosted on GCP

### Platform(s)

iOS

### Current Behavior

Having 2 channels (dev & prod), each with some of the same versions and some different. Prod channel is default
ie

dev: 1.0.343, 1.0.371
prod: 1.0.343

Calling `getLatest` on `dev` channel, returns "1.0.343" (prod) version even though it is not latest when my package.json>version is the same as dev latest. Can see this in web console as well:

<img width="999" alt="image" src="https://github.com/Cap-go/capacitor-updater/assets/58610870/97299c76-85f4-4dd1-8ad7-894d3e1f31ec">

Overall with my testing:
package.json>version: 1.0.350 -> getLatest() returns 1.0.343 from production channel
package.json>version: 1.0.371 -> getLatest() returns 1.0.343 from production channel
package.json>version: 1.0.372 -> getLatest() returns 1.0.371 from dev channel

### Expected Behavior

A targetted channel should return latest version for that channel

### Other Technical Details

`npm --version` output: 9.6.7

`node --version` output: v18.17.1

`pod --version` output (iOS issues only): 1.12.1

**Comment by riderx** [comment]
Can we check than Monday together ?
