### ISSUE TITLE
feat: allow update endpoint to return custom json data object

### ISSUE THREAD

**Issue by alexcroox** [Cap-go/capacitor-updater#300]
### Description

I would be great for self hosted API users if we could send back additional data from the update endpoint that is surfaced to the client JS via the plugin bridge. This is useful to fine tune update behaviour based on data/flags from the database.

### Platform(s)

ios/android

### Preferred Solution

When returning the update response, support a generic data object:

```
return {
  url: 'https://example.com/1.zip',
  version: '1.2.3',
  data: {
    isForcedUpdate: true // the keys of the data object could be anything 
  }
}
```

Then in the client:

```
const latestUpdate = await CapacitorUpdater.getLatest()

console.log('Is forced update?', latestUpdate.data?.isForcedUpdate)
```

Thank you!

**Comment by riderx** [comment]
Good idea! You should be able to use it in [5.6.0](https://github.com/Cap-go/capacitor-updater/tree/5.6.0)

**Comment by alexcroox** [comment]
Amazing thank you!!
