### ISSUE TITLE
Launch paid offers

### ISSUE THREAD

**Issue by riderx** [Cap-go/capacitor-updater#31]
<p>I’m thinking to have 3 tiers pricing + freemium</p>

  | Solo | Maker | Team
-- | -- | -- | --
App | 1 | 3 | 10
Channels per app | 2 | 10 | 50
Versions history per app | 10 | 100 | 1000
monthly update per app | 2,500 | 25,000 | 250,000
Sharing per app | No | 10 | 100
Price | $14 by month | $39 by month | $99 by month

**Comment by berkayyildiz** [comment]
What is sharing per app?

**Comment by riderx** [comment]
@berkayyildiz when you use the capgo sandbox, you can test each version inside the sandbox, and you can share it to your team too.
So, this is the limit of your team members who can try the app in the sandbox.
You can find more about the sandbox app here: https://github.com/Cap-go/capacitor-updater/wiki/Capgo-Sandbox-App
