### ISSUE TITLE
bug: After i update using download method ...the version didn't updated...it still remains in previous version  

### ISSUE THREAD

**Issue by muruganmari** [Cap-go/capacitor-updater#311]
### Capacitor Version

```
PASTE OUTPUT HERE
```

### Plugin Version

```
PASTE OUTPUT HERE
```

### context(s)

```md
ManualModel: false
AutoMode: false
CapgoCloud: false
OnPremise: false
```

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by riderx** [comment]
Please fill the template if you want help
