### ISSUE TITLE
Add progressive deploy

### ISSUE THREAD

**Issue by riderx** [Cap-go/capacitor-updater#36]
The goal to this is to allow X% of the user base receive the update

See if that fine for them, and continue to have more, until 100%

**Comment by timdelange** [comment]
Maybe have a device/install/uniqueID in the update request header, then serve different updates to different device Id's passed in the headers. Could also help with a/b testing if you make it easy to manage specific devices.

**Comment by riderx** [comment]
DeviceId is already send in the body of update request.
What is missing now is the backend side, and the UI to allow select multiple versions

**Comment by roxanne-mackinnon** [comment]
I am currently working on this.

**Comment by rishi-raj-jain** [comment]
@riderx Can I work on this?

**Comment by riderx** [comment]
Yes or course !

**Comment by rishi-raj-jain** [comment]
I'd be passing on this for now, focusing https://github.com/Cap-go/website/pull/103

**Comment by riderx** [comment]
okay thanks for the info

**Comment by riderx** [comment]
@WcaleNieWolny i think you have a chance to check this as well

**Comment by riderx** [comment]
it could be nice to set % of user should receive new update, while other receive old one. like AB
By the way we cannot activate AB and progressive for me.
With progressive we want to set 10% and when this amount is reached receive email said it was done.

**Comment by WcaleNieWolny** [comment]
I will work on this, I just have to finish AB testing

**Comment by WcaleNieWolny** [comment]
I believe this should be in a way that you have either ab tests or this, this removes code duplication. Would that be fine?

**Comment by WcaleNieWolny** [comment]
> See if that fine for them

This is not so clear for me. Technically we have `update_fail` stat, however not so sure how well that will work

**Comment by WcaleNieWolny** [comment]
I believe we could just blindly increase the % of users with the B version and implement a panic kill switch that would do the following steps:

 - disable progressive deploy
 - if % reached 100:
   Swap version A and B (after reaching 100% we would swap A and B and this would just reverse that making version B the bad version and version A the version before the bad change)
 - remove version B (delete it from S3 etc)

**Comment by riderx** [comment]
I’m not sure to understand, the event update fail is attached to version, the one returned is not the right one ?

**Comment by WcaleNieWolny** [comment]
Well no, it is the version that was downloading the update (in this case `1.0.0` failed to download `1.3.x`)

**Comment by WcaleNieWolny** [comment]
version of id `1884` is the build-in version
![image](https://github.com/Cap-go/capacitor-updater/assets/50914789/f7edf0be-10ff-45fa-a750-daac86250790)

**Comment by riderx** [comment]
This is a bug then ^^, look here:
![CleanShot 2023-08-19 at 13 07 43@2x](https://github.com/Cap-go/capacitor-updater/assets/4084527/aa88b009-63ea-43e2-9f38-9e999b34915a)

**Comment by WcaleNieWolny** [comment]
Well it is also possible I have broke something, but I will attempt to debug this. If I find anything weird with this I will create an issue

**Comment by riderx** [comment]
i think it's a buck in backend:
![CleanShot 2023-08-19 at 13 12 04@2x](https://github.com/Cap-go/capacitor-updater/assets/4084527/a1187139-5e87-4aed-922d-d24059511d83)
And created here:
![CleanShot 2023-08-19 at 13 13 14@2x](https://github.com/Cap-go/capacitor-updater/assets/4084527/62a13e97-d0c9-41ce-bedc-f85f2e921b3e)

**Comment by WcaleNieWolny** [comment]
I will finish AB testing (debugging right now) and I will work on debugging this

**Comment by WcaleNieWolny** [comment]
![image](https://github.com/Cap-go/capacitor-updater/assets/50914789/9d414829-67f3-45cd-acf4-7498a6fcbabd)
![image](https://github.com/Cap-go/capacitor-updater/assets/50914789/101c78fd-5f6c-4882-8eb6-0891fa2fc13e)

**1)** version does not exists, at least android does not send version

**Comment by WcaleNieWolny** [comment]
![image](https://github.com/Cap-go/capacitor-updater/assets/50914789/bd97615c-e395-4547-9f2d-9982df08d7c8)

 ```js
     .order('id', { ascending: false })
 ``` 
 ([here](https://github.com/Cap-go/capgo/blob/9c9353cad8385ced93ae89559868886d661cb88b/supabase/functions/stats/index.ts#L91))
 
 This is not the best way to handle version selection. First of all this is in the descending order meaning that by default it will grab the "buildin" version (as build in has id `1884` which is the largest value) and second of all I do not understand why there is a `name.eq.builtin`. I was able to fix that by setting `ascending` to false, but this solution will break once app exceeds ~1800 uploads

**Comment by riderx** [comment]
The version was from old plugin system, thanks i removed it

**Comment by riderx** [comment]
For the second point i don't understand, why it will stop after 1800 ?

**Comment by WcaleNieWolny** [comment]
Well if we set the order of the request to ascending (lowest if first) then if `app_versions.id > 1884`  (1884 is ID of the default `builtin` version) then we would have `[(ID: 1884, name: builtin), (ID: 2000, name: version_name)` and then `appVersion` in the code I sent would be set to the builtin version essentially causing the bug all over again

**Comment by WcaleNieWolny** [comment]
Here is my plan for this:

 * Add a switch for progressive deploy (cannot have both AB tests and progressive deploy, nor change the % slider from AB testing when progressive deploy is on)
 
![image](https://github.com/Cap-go/capacitor-updater/assets/50914789/9a584a3f-e978-4227-89e9-766ea831e2b2)
![image](https://github.com/Cap-go/capacitor-updater/assets/50914789/7df968bf-7e6d-42f8-b281-fa64cb1720af)
![image](https://github.com/Cap-go/capacitor-updater/assets/50914789/e5bc8724-a186-4bc9-89db-9adb201a3d9d)

 * Change the channel UI to inform about status of progressive deploy
 
![image](https://github.com/Cap-go/capacitor-updater/assets/50914789/1658c298-dc62-4f9a-bef7-2eead3677ac5)
![image](https://github.com/Cap-go/capacitor-updater/assets/50914789/51ec5d3c-36b8-4b9b-9b8a-f65e68c2d54e)

 * Make sure that when uploading from CLI user gets informed about progressive deploy and if progressive deploy is enabled upload to progressive deploy instead the main version
 * Make sure the CLI informs if latest progressive deploy has not yet finished (in this case, we still proceed)
 
![image](https://github.com/Cap-go/capacitor-updater/assets/50914789/d872d433-757a-4caf-b49a-c7d8ab2411a6)

 * Make sure that on manual version linkage to channel user has the option to skip progressive deploy

![image](https://github.com/Cap-go/capacitor-updater/assets/50914789/46f29b92-64ea-4f10-b1cb-84131be2bdfb)

 * Write a cron API job that every 10 mins will increase the secondary version percentage for channels where no `update_fail` events have occurred (If in the last hour the progressive version has triggered `update_fail` do not trigger % change and potentially disable progressive uploads all together to prevent the spreading of an bad update)
 (I intend this cron job to be an SQL query if possible)

**Comment by WcaleNieWolny** [comment]
@riderx please let me know if you need anything more from this. About that email. I am not sure it is needed. A failed update should trigger an email already

**Comment by WcaleNieWolny** [comment]
https://github.com/Cap-go/capgo/pull/294

Here is the PR for this issue
