### ISSUE TITLE
bug: Updates doesn't works on Android 14 (SDK 34)

### ISSUE THREAD

**Issue by kalanda** [Cap-go/capacitor-updater#369]
## Bug Report

BroadcastReceiver of CapacitorUpdater class is never called by intents of the DownloadService, so updates never happens.

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

Installed Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Plugin Version

```
│
●   💊   Capgo Doctor  💊
│  
│
●   OS: darwin Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:49 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6020
│  
│
●   Node: v18.17.1
│  
│
●   Installed Dependencies:
│  
│
●     @capgo/cli: 4.10.3
│
●  
│  
✓   Latest Dependencies:
│
●     @capgo/cli: 4.10.3
│
◆  ✅ All dependencies are up to date
```

### context(s)

```md
ManualModel: false
AutoMode: true
CapgoCloud: false
OnPremise: false
```

### Platform(s)

- Android 14 (SDK 34)

### Current Behavior

Since we did the upgrade to Capacitor 6 and @capgo/capacitor-updater 6, when running in Android 14 API SDK level 34 (either inside physical device or inside emulator) the BroadcastReceiver of CapacitorUpdater class is never called by intents of the DownloadService, so seems like `dist.zip` file is downloaded fine but never processed by CapacitorUpdater and update never happens. It works fine in previous versions of Android (SDK 33 and below) and iOS too.

### Expected Behavior

CapacitorUpdater class should be notified to process update file from DownloadService. 

### Additional Context

As you can find at comment 16 of this issue (https://issuetracker.google.com/issues/293487554#comment16) the issue is solved by adding `intent.setPackage(getPackageName())` when `RECEIVER_NOT_EXPORTED` is used.

I made the changes in my local version of the package and it works fine. 

### Solution

Created this PR with the fix https://github.com/Cap-go/capacitor-updater/pull/370

**Comment by riderx** [comment]
Thanks a lot for the report and the fix i merged it
