### ISSUE TITLE
Add AB testing features

### ISSUE THREAD

**Issue by riderx** [Cap-go/capacitor-updater#37]
Allow 50% to have one version and 50% to have other to see if that improve specific stat

**Comment by tachyonicbytes** [comment]
Hi! I would like to work on this!

/claim #37

**Comment by riderx** [comment]
@tachyonicbytes let go i will share with you more details then.
I believe this task has to be done in https://github.com/Cap-go/capgo
What need to be done:
- allow in the web to set into a channel version A and B
- allow in a channel to set % for A and B
- make update endpoint do a random prob between A and B
- Display in the channel the distribution of A and B

**Comment by tachyonicbytes** [comment]
Is the channel sufficient for collecting the test results? As I see it, the type A or B has to be associated with the client, in order to collect the test results. Theoretically, it may go down to two metadata points, a "is client part of A/B testing", and "A/B testing type". The latter may be enough though.

**Comment by WcaleNieWolny** [comment]
Since this has not been active for a long time I am attempting this

**Comment by WcaleNieWolny** [comment]
Here are my changes so far:
![image](https://github.com/Cap-go/capacitor-updater/assets/50914789/56b1dc9c-79f0-4bb5-833f-3c76b42c301d)

**Comment by WcaleNieWolny** [comment]
I also would like to ask: How should we handle the %? How do I update this without causing a spam to the supabase? If I update this on every change this will generate A LOT of requests

**Comment by WcaleNieWolny** [comment]
![image](https://github.com/Cap-go/capacitor-updater/assets/50914789/e53d682a-4a0b-4a13-8847-3106e512f6f7)

You cannot have 1 bundle on multiple channels:
![image](https://github.com/Cap-go/capacitor-updater/assets/50914789/7cbf4582-3db9-401f-bb1f-7188cea9d270)
(It will unlink the other channel if you attempt this, not sure how to handle when users attempts to set bundle on 2 AB channels at once)

![image](https://github.com/Cap-go/capacitor-updater/assets/50914789/16cf6165-3850-45f3-88fa-f80063cf9144)
Linking also works

**Comment by WcaleNieWolny** [comment]
Please let me know if that was what you was hoping for @riderx

**Comment by riderx** [comment]
@WcaleNieWolny just a debounce on the % will be good i believe !
Pretty cool, i just wonder how user will use this, like how they will measure they test

**Comment by WcaleNieWolny** [comment]
I would like to confirm:

`if (!signedURL || signedURL.startsWith('http://') || !signedURL.startsWith('https://'))`

Is this the intended behavior? I do not understand why HTTP without TLS would be disallowed to be honest

**Comment by riderx** [comment]
@WcaleNieWolny because on android it’s disabled by default, so if you try http you will have that to work only in iOS .
So I made the plugin behave the same in both

**Comment by WcaleNieWolny** [comment]
Oh, okay in that case. I will just not commit my change and just use this in local testing
