### ISSUE TITLE
bug: Plugin not showing in js / window.Capacitor.Plugins

### ISSUE THREAD

**Issue by HeikoWitthoeft** [Cap-go/capacitor-updater#391]
### Capacitor Version

```
5.7.6
```

### Plugin Version

```
6.0.31
```

### context(s)

```md
ManualModel: false
AutoMode: true
CapgoCloud: false
OnPremise: true
```

### Current Behavior

The Plugin is not available after building our IOS app in the plugins collection of window.Capacitor.Plugins as other Plugins are.
For Android it whows up on that place.

### Expected Behavior

Should be available in the Plugins collection.

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by HeikoWitthoeft** [comment]
aha, we made it work by adding capacitor core and adding manually the dist/plugin.js file - but every call to the plugin is denied by an: "Plugin is not supported by ios platform" Maybe one of you can bring some light. Thanks

**Comment by WcaleNieWolny** [comment]
I think you should use capacitor 6.0 with the 6.0 plugin

**Comment by HeikoWitthoeft** [comment]
Thanks - we will try
