### ISSUE TITLE
bug: setmultiDelay killing option not working on android 14

### ISSUE THREAD

**Issue by riderx** [Cap-go/capacitor-updater#404]
## Bug Report
I got some report of update not happening after app kill on android 14.

This should properly skip the update and install in next background 

How to reproduce:
Add in your code: 
```js
await CapacitorUpdater.setMultiDelay({
      delayConditions: [ { kind: "kill" } ]
    })
```
Push new version to CapGo server
Open the app
Wait for the update to Download
( set shouldn't be done)
Kill the app
Open it again
Background app
Open again
( set should happen ) It seems it only work on iOS

**Comment by varshith257** [comment]
@riderx Some more description of the issue and a way for fix will help to quickly dig into the issue :)

**Comment by riderx** [comment]
Should be fixed in https://github.com/Cap-go/capacitor-updater/releases/tag/6.0.65
