### ISSUE TITLE
feat: replace checksum with sha256

### ISSUE THREAD

**Issue by WcaleNieWolny** [Cap-go/capacitor-updater#431]
Currently, the checksum impl is very dumb. It will do decryption BEFORE verifying the checksum.

I propose that we replace the checksum with sha256 to remove this bug

**Comment by riderx** [comment]
sha256 does not change anything related to the moment we do checksum.
So 2 issue

**Comment by WcaleNieWolny** [comment]
Checksum was switched to sha256
The order stated the same and it won't be changed.

Won't fix.
