### ISSUE TITLE
Question: defaultChannel not used but as option - why?

### ISSUE THREAD

**Issue by Dexus** [Cap-go/capacitor-updater#461]
For what is the `defaultChannel` that is set but not used on the code. For what is it?

**Comment by riderx** [comment]
I'm not sure to understand the question?
defaultChannel is used by the CLI to device on what channel upload if none is provided

**Comment by Dexus** [comment]
I was wondering because its send to the plugin code, but had the no usage. So i was not sure, why it is there and the information to this prop is not clearly for me.
