### ISSUE TITLE
bug: GetChannel is not returning the current channel set from defaultChannel

### ISSUE THREAD

**Issue by riderx** [Cap-go/capacitor-updater#486]
### Capacitor Version

```
PASTE OUTPUT HERE
```

### Plugin Version

```
PASTE OUTPUT HERE
```

### context(s)

```md
ManualModel: false
AutoMode: false
CapgoCloud: false
OnPremise: false
```

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by WcaleNieWolny** [comment]
Already done
