### ISSUE TITLE
Add versionCode header in auto update mode on android 

### ISSUE THREAD

**Issue by cosic-dalibor** [Cap-go/capacitor-updater#56]
On Android currently the request sent to the server to check for auto updates is including header cap_version_build which has the value of versionName value from android project. Since versionName is free text it might be useful to introduce a new header containing versionCode value from android project since versionCode is unique while versionName can free text.

**Comment by riderx** [comment]
i always thought the versionName was more trustable, because it's the case in ios.
good to know i will send it in next version in header

**Comment by cosic-dalibor** [comment]
Thanks.

**Comment by riderx** [comment]
This has been added in the `3.1.0` :)
