### ISSUE TITLE
iOS exception (EXC_BAD_ACCESS)

### ISSUE THREAD

**Issue by alexmelville7** [Cap-go/capacitor-updater#57]
Version 3.0.3.

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/41615914/164216094-5fdc4cf8-14f8-46e4-b9f2-28e291710a1f.png">

This happens when the app starts up. Not sure what the is causing this.

**Comment by riderx** [comment]
Hello alex thanks for the report, i don't have this on my app, can you create a reproduction repo to help me fix it ?
