### ISSUE TITLE
R&D download before start first open

### ISSUE THREAD

**Issue by riderx** [Cap-go/capacitor-updater#72]
TO have the same behavior as Burger king app
![IMG_4103](https://user-images.githubusercontent.com/4084527/166567694-94d414bf-294b-4a0d-bf9b-aba5d12788dc.png)
We could use a wording like : 'We are optimizing your app experience'

**Comment by meilechwieder** [comment]
This is R&D for auto-update, note for manual is it's already possible.

**Comment by Alcadeus0** [comment]
Hello, I'd like to work on this issue :)

**Comment by riderx** [comment]
Hi @Alcadeus0 that awesome ! please feel free to ask here any missing info

**Comment by Alcadeus0** [comment]
@riderx How do I reproduce this issue?

**Comment by riderx** [comment]
@Alcadeus0 you can use the demo app:
https://github.com/Cap-go/demo-app

Acceptance criterial:
- updated should be download and apply at first launch
- a loader is visible while the download happen
- works both in ios and android
- no code duplication

**Comment by Alcadeus0** [comment]
@riderx running `npx cap verify` gives me 
![image](https://user-images.githubusercontent.com/59562284/230715944-97b6f605-de40-408a-9729-0e133f0a1975.png)
is this output expected?

**Comment by riderx** [comment]
this command run from the CI and in local, did you run the command in the root folder?

**Comment by Alcadeus0** [comment]
yes I'm running in the root folder, maybe that's why

**Comment by riderx** [comment]
mmm ok sorry, you have to have the package manager cocoa pods and use a mac.
This task is pretty hard, good knowledge in ios/android is recommended.
plus you have to understand capacitor env

**Comment by Alcadeus0** [comment]
Sure, I'll give it a shot

**Comment by ayewo** [comment]
Here goes nothing while I /attempt #72 .

**Comment by riderx** [comment]
Hey @ayewo i made half of this working, it's done in IOS i still have some issue in Android.
Have you something on your side ?

**Comment by ayewo** [comment]
Hi @riderx 

> Maybe we can join forces

You've already done 50% do I really have a choice 😀?

Since you've coded the iOS implementation, perhaps you could share it so I can translate it for Android.

**Comment by riderx** [comment]
I'm sorry, I really needed it, and a shower showed me the way ^^.
I just finished the Android part as well 5 min ago.

So the bounty in this state is not available anymore.
I would more now try to battle test it, and be sure this work 100% of the time.
 Can you help on that ?
 I can do 100 bounty for this

**Comment by ayewo** [comment]
Haha @ shower thoughts 😁

Sure. I updated the capacitor-related dependencies for the [demo-app](https://github.com/Cap-go/demo-app) from v4.x.x to v5.x. and will share that later.

Is that what you used for initial testing.

**Comment by ayewo** [comment]
Hey Martin @riderx,

Testing on iOS and Android ended up taking quite a bit of time ... I think some refactoring and/or some unit tests will be useful—especially for the partial download feature—as I ran into some scenarios where some bundles were failing to delete. 


### Miscellaneous Issues
- On Android, I did get the occasional `A resource failed to call release` so there's a resource leak somewhere.
- The CLI seems to output an invalid URL at the end of a bundle upload. Towards the end, it will offer the following 404 URL https://web.capgo.app/app/p//logs in its output (or maybe I don't have authorization to see it?):
```js
●  Check logs in https://web.capgo.app/app/p//logs to see if update works.
│
●  Welcome onboard ✈️!
│
●  Your Capgo update system is setup
│
●  Next time use `npx @capgo/cli@latest bundle upload` to only upload your bundle
│
└  Bye 👋
```

**Comment by riderx** [comment]
I think you are right i never tested end to end local env so that could be broken, if you need time to fix it i can do bounty for that

**Comment by ayewo** [comment]
The demo app worked on both iOS and Android in my testing. Had to fix a minor logic bug in the demo app (the Splashscreen was shown too quickly) and fixed a minor bug in the iOS plugin.

For the miscellaneous issues, I can open a separate ticket for them later as they’ll require time for me to investigate and fix them. 

Right now, I’m trying to complete the work I started on #119 so please accept the PRs I opened for this issue:
- https://github.com/Cap-go/capacitor-updater/pull/242
- https://github.com/Cap-go/demo-app/pull/29

Thanks!

**Comment by FernetB** [comment]
Hi!, i have a question

Where i can see how to make a loading page with `auto update: true` and `direct: true`?

**Comment by riderx** [comment]
You can find it here:
https://capgo.app/docs/plugin/force-update/#direct-update
