### ISSUE TITLE
R&D: Should it be possible to delete the currently active bundle?

### ISSUE THREAD

**Issue by lincolnthree** [Cap-go/capacitor-updater#77]
It is currently possible to delete the current active distribution.zip bundle from the local filesystem.

I think it might be safer if this threw an error, but I'm not 100% sure.

What should the behavior be in this scenario where the user deletes the active bundle files? The effect of this is that the app will essentially stop working. Any JS/HTML that has not yet loaded will result in 404 errors once this happens.

**Comment by riderx** [comment]
Oh yes you are right it shouldn't be possible

**Comment by riderx** [comment]
Hey @lincolnthree i just added it in V4, thanks for the suggestion
