### ISSUE TITLE
Manual set on IOS don't work

### ISSUE THREAD

**Issue by PIXPOINT** [Cap-go/capacitor-updater#80]
Unfortunately, the `set` function in IOS does not work. According to the logs, everything worked, but after reloading the app, the old version is still active. No errors appear in Xcode.

The same thing happens when I use the autoupdate function.

What is worthwhile: When I create a new version with `npx cap copy ios,` it is only active after I have performed the `reset` function.

Does anyone have any idea why this might be?

Update code:
```js
console.log("UPDATE: START");

let data = await CapacitorUpdater.download({
    url: 'https://myserver.com/dist.zip',
});
if (data.version !== '') {
    try {
        console.log("UPDATE: SET");
        await CapacitorUpdater.set(data);
    } catch (err) {
        console.log("UPDATE: ERROR", err);
    }
}
```

Logs:
```md
 To Native ->  CapacitorUpdater download 3038699
⚡️  [log] - UPDATE: START
⚡️  TO JS {"version":"5SQ0ROij8f"}
⚡️  [log] - UPDATE: SET
⚡️  To Native ->  CapacitorUpdater set 3038700
✨  Capacitor-updater: Stats send for set, version 5SQ0ROij8f
✨  Capacitor-updater: Reload app done
✨  Capacitor-updater: Set to version: 5SQ0ROij8f versionName: 5SQ0ROij8f
```

**Comment by riderx** [comment]
Hello @PIXPOINT sorry for the late delay, can you provide a reproduction repository ?
it will help me better catch your issue
