### ISSUE TITLE
Only apply update on the next app start

### ISSUE THREAD

**Issue by co-dax** [Cap-go/capacitor-updater#84]
Need to allow to prevent applying update when app goes in the background in auto update mode.
`delayUpdate` has similar behavior but it is only skipping update applying when the app goes the first time in background while it would actually apply the downloaded update on the second switch to background.

thus, we need this `newsetBackgroundUpdateEnabled`(true/false) function to essentially indicate that the update will only have to be applied on the next app start;
after the update has been downloaded, the update should not be applied when switching between background and foreground several times, but it should be only applied on the next app start.

Lincoln had suggested function name like `setBackgroundUpdateEnabled`(true/false).

**Comment by riderx** [comment]
Hey @co-dax thanks for the suggestion, i added this option in the v4, who is currently in beta, if you wanna try it
