### ISSUE TITLE
Internationalization of all texts

### ISSUE THREAD

**Issue by ajjp** [Cap-go/capacitor-updater#87]
As far as I could see all texts are in english which might not be user-friendly to non-english spoken users

**Comment by riderx** [comment]
Thanks, do you have ressources to learn how to fix it ?

**Comment by theinfosecguy** [comment]
@riderx Is this for the whole website or only GitHub Docs (such as README)?

**Comment by riderx** [comment]
the webapp is already translated, it's about internationalization in android and ios plugin.
basically the logs.

**Comment by ajjp** [comment]
Hi @riderx, I would like to help, do you have any text/json/whatever files to translate?

**Comment by riderx** [comment]
The need is about understanding how to implement internationalization in android and IOS, create it, find the keys to transform them in translatable key.

For translation i have deepl that not the issue

**Comment by akshaydoshi2** [comment]
Hi @riderx I can work with implementing internationalization in android and iOS and set up the translatable key value pairs . Can you point me to the strings?

**Comment by riderx** [comment]
@akshaydoshi2 i have never done I18n on IOS android so i cannot help much ^^

**Comment by akshaydoshi2** [comment]
> @riderx I will work with the I18n for iOS and Android. No worries about that. But it would be great if you could let me know which all text needs to be translated and added to I18n. That is all I need.

@riderx can you please update on this?

**Comment by akshaydoshi2** [comment]
> @akshaydoshi2 i think your translation work is missing in android

Hey @riderx I have fixed that and created a new PR.

**Comment by riderx** [comment]
will not do for now
