### ISSUE TITLE
iOS update occasionally fails to copy some files.

### ISSUE THREAD

**Issue by playaz87** [Cap-go/capacitor-updater#98]
We've had a few reports from users after an update that the app is broken. Based on screenshots we've been sent, in some cases it looks like the css files are missing and other cases some image assets are missing. 

Reloading the app doesn't solve the issue but, if they uninstall the app, download again from the App Store and then reinstall the web app update, it works. 

This points to it not being a device or configuration issue. Perhaps a corrupt download? A nice feature would be to be able to provide a checksum to `CapacitorUpdater.download()`.

**Comment by riderx** [comment]
@playaz87 you use the manual mode right ?
checksum is on the roadmap, it's a must have i agree !

**Comment by playaz87** [comment]
Yes, I do. Any eta on the checksum?

**Comment by riderx** [comment]
i have to check probably with the v4 mi august

**Comment by playaz87** [comment]
@riderx Great, I'll keep an eye out!

**Comment by riderx** [comment]
@playaz87 can you share a code reproduction for this issue, i have check and the checksum issue could only happen if security corruption, checksum is implemented at os level

**Comment by playaz87** [comment]
@riderx I don't know if it's an issue specific to our app or a general issue so I can't really provide a repo.

Our app checks our server to see if there's an update. If an update is available the server sends the download link. I'd like to be able to send a checksum for the zip file along with the download link so that the plugin can compare the downloaded file with the checksum.

**Comment by riderx** [comment]
@playaz87 i was able today to reproduce your issue with image missing !
i try to understand it now

**Comment by playaz87** [comment]
@playaz87 It's a weird one. We've downgraded to `2.3.3` which I've used in another project without issue. We haven't had any complaints yet, but it's only been 2 weeks and 1 update.
