### ISSUE TITLE
autoUpdate is not working in android emulator

### ISSUE THREAD

**Issue by simonflk** [Cap-go/capacitor-updater#99]
Hi, I've been testing out capgo for use in our app since yesterday. It looks great - thank you for all your hard work putting this together and making it open source.

I have enabled `autoUpdate` and verified that this works ok in the iOS simulator.
However I could not get this to work on the Android emulator, but before I get on to that, I just verified on a real android device that this works as expected. 

So for me this issue is limited to the android emulator. In debug mode, I see this in the logs. Unfortunately, Android Studio has just gone non-responsive, so I cannot copy/paste the error logs. A screenshot will have to suffice:

<img width="928" alt="CleanShot 2022-08-18 at 16 11 49@2x" src="https://user-images.githubusercontent.com/4867329/185416512-10e8e274-d875-48dc-a4c1-8febd730f9b4.png">

For searchability, I'll retype the important bit here:
```
I/Capacitor-updater: Check for waiting update
I/Capacitor-updater: Check for update in the server
E/Capacitor-updater: error downloading file
   javax.net.ssl.SSLHandshakeException: Chain validation failed
      at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:363)
...
```

## Environment:

OS: macOS Monterey 12.5.1 
Emulator: Pixel 5 API 31

Capacitor plugins:
```
@capacitor/android: 3.6.0
@capacitor/app: 1.1.1
@capacitor/cli: 3.6.0
@capacitor/core: 3.6.0
@capacitor/device: 1.1.2
@capacitor/ios: 3.6.0
@capacitor/push-notifications: 1.0.9
@capacitor/splash-screen: 1.2.2
@capacitor/storage: 1.2.5
@capgo/capacitor-updater: 3.3.17
@robingenz/capacitor-app-update: 1.3.1
```

**Comment by riderx** [comment]
Hey Simon thanks for the report, i never saw this error before, can you provide a reproduction repo ?
That will make my job way more easier to understand your issue !

**Comment by luca-sharryland** [comment]
Hi @simonflk, for the first time yesterday I encountered this error. The problem is the wrong date or the wrong time set in the emulator. So if you delete the device in "active device" and reinstall it, you will solve the problem.

**Comment by simonflk** [comment]
Thank you @luca-sharryland I will try that

**Comment by riderx** [comment]
@simonflk any news?
